### ISSUE TITLE
ptipython does not run ipython startup script

### ISSUE THREAD

**Issue by linyuxu** [prompt-toolkit/ptpython#126]
ptipython is awesome! I use it to replace ipython. But I found ptipython do not execute the ipython startup files, e.g. **~/.ipython/profile_default/startup/***

I did a local patch to make this done, i.e. modify **site-packages/ptpython/ipython.py**, replacing "embed" function with the following code:

```
def embed(**kwargs):
    config = kwargs.get('config')
    header = kwargs.pop('header', u'')
    compile_flags = kwargs.pop('compile_flags', None)
    if config is None:
        config = load_default_config()
        config.InteractiveShellEmbed = config.TerminalInteractiveShell
        kwargs['config'] = config
    shell = InteractiveShellEmbed.instance(**kwargs)
    initialize_extensions(shell, config['InteractiveShellApp']['extensions'])
    RunStartupScripts(shell)
    shell(header=header, stack_depth=2, compile_flags=compile_flags)

def RunStartupScripts(shell):
    import glob
    import os
    startup_dir = shell.profile_dir.startup_dir
    startup_files = []
    startup_files += glob.glob(os.path.join(startup_dir, '*.py'))
    startup_files += glob.glob(os.path.join(startup_dir, '*.ipy'))
    for file in startup_files:
        shell.run_cell(open(file).read())
```

But is it OK to support this feature officially.

**Comment by yamsu** [comment]
Yeah this is a good work around. Please do include this is the official release.

**Comment by kbd** [comment]
Just came here to report this. I, too, was surprised when `ptipython` didn't pick up my `ipython` config. Is there any solution besides patching the program code in `site-packages`?

**Comment by vict0rsch** [comment]
No news on this front?

**Comment by ned2** [comment]
Would really love to see this fixed. This is a friction point for using `ptipython` as a replacement for `ipython`.

@jonathanslenders do you have any thoughts about directions for fixing this? Might be able to work on a PR but would need some guidance.
