### ISSUE TITLE
Please use XDG paths for config.py and history by default

### ISSUE THREAD

**Issue by z0rc** [prompt-toolkit/ptpython#132]
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been around for several years already. Please use recommended folders for storing `config.py` and `history` files.

`config.py` should be stored in `$XDG_CONFIG_HOME/ptpython/config.py` with fallback to `$HOME/.config/ptpython/config.py` if `$XDG_COFIG_HOME` is not set. You may fall back to `$HOME/.ptpython/config.py` is it wasn't found at XDG path and this file is present.

`history` should be stored in `$XDG_DATA_HOME/ptpython/history` with fallback to `$HOME/.local/share/ptpython/config.py` if `$XDG_DATA_HOME` is not set. Again you may fall back to `$HOME/.ptpython/history` if it wasn't found at XDG path and this file is present.

Ideally application should warn user that he is using legacy configuration path or just migrate automatically existing `config.py` and `history` to new locations.

Grand plan behind all of this is to eliminate dotfiles clutter from user's home folder.

**Comment by DanCardin** [comment]
Annoyingly appdirs ignores `XDG_*_HOME` on darwin, so this is actually a regression from the previous behavior where (given that I set `XDG_CONFIG_HOME` to `~/.config`) i could just have `~/.config` be a git repo of my config.

I realize this is more of a bug with appdirs but, it's manifesting in a behavioral change here :(
