### ISSUE TITLE
ptpython Debian package

### ISSUE THREAD

**Issue by cdluminate** [prompt-toolkit/ptpython#207]
Temporary working but hacky package available here
http://debomatic-amd64.debian.net/distribution#experimental/ptpython/0.39~1/buildlog

This is still a work in progress.

http://debomatic-amd64.debian.net/debomatic/experimental/pool/ptpython_0.39~1/python-ptpython_0.39~1_amd64.deb
http://debomatic-amd64.debian.net/debomatic/experimental/pool/ptpython_0.39~1/python3-ptpython_0.39~1_amd64.deb

**Comment by justinlulejian** [comment]
Package links don't work anymore.

I've been doing this step as a workaround after installing with pip. https://github.com/jonathanslenders/ptpython/issues/207
