### ISSUE TITLE
Embed ptpython repl in a prompt_toolkit app

### ISSUE THREAD

**Issue by JonasVautherin** [prompt-toolkit/ptpython#290]
Would it be possible to embed ptpython repl as an element of a prompt_toolkit app, or doesn't it make sense at all?

I just discovered prompt_toolkit (and ptpython) and I am playing with them. I am wondering if I could:

1. Create a prompt_toolkit app that would show some data (say something like the output of the `top` command) in a window, and the ptpython repl in another.
2. If 1. is possible, could I use the repl in order to edit the running app? Like adding windows etc?

That would make a super cool playground :-).

**Comment by JonasVautherin** [comment]
Is that the right place to ask, or should I have asked in prompt_toolkit? :Confused:

**Comment by jonathanslenders** [comment]
Hi @JonasVautherin,

I think, right now, without any modification to ptpython itself, it will be very hard.

However, have a look at this example: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/full-screen/calculator.py
That's a very simple Python REPL in a full screen application. It should be possible to expose the application object itself in the REPL. Further, you can use the completer from ptpython to have Jedi-based auto completion. (Possibly you have to add a CompletionMenu to the layout.)

**Comment by JonasVautherin** [comment]
Great, I'll play with that and I'll try to understand the [`PythonCompleter`](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/completer.py#L16) :-).

I just was wondering if there was a trivial way to do that with `embed` instead of reinventing the wheel. I'll let you know if I end up somewhere!
