### ISSUE TITLE
ptipython thinks top-level await is invalid syntax

### ISSUE THREAD

**Issue by NotAFile** [prompt-toolkit/ptpython#306]
compare the following snippet in ptipython and ipython:

```
In [1]: import asyncio

In [2]: await asyncio.sleep(0)
```

In IPython, this works fine, but in ptipython, it is not accepted, as it is thought to be invalid syntax. Turning off input validation fixes this (except for the syntax hightlighting). However, I think it should be possible to use await outside of functions even with input validation turned on.

**Comment by jonathanslenders** [comment]
Hi @NotAFile,

The input validator does indeed not yet handle this situation, it has to be fixed. A work-around for now is indeed to disable the input validation.

**Comment by butla** [comment]
Does this mean I'll be able to just do `await coroutine()` in the REPL? That'd be awesome :)

**Comment by NotAFile** [comment]
@butla this has already long been a feature of ipython, this just makes ptipython aware of it

**Comment by butla** [comment]
@NotAFile Yup, I know, but I prefer ptpython :)
