### ISSUE TITLE
Clear the screen

### ISSUE THREAD

**Issue by jebr** [prompt-toolkit/ptpython#349]
Hi there, 
I just started using ptpython and can't find a way to clear the console. Is there a command or a function for this?

**Comment by zhichaoh** [comment]
I cannot seems to find a way. I have tried to run shell command cls on windows 10. It throws exception about run_system_command was never awaited instead of clearing the console.

**Comment by jebr** [comment]
I've tried `clear `and `clear()` but it throws me a NameError exeption.

**Comment by zhichaoh** [comment]
I think you have to run the shell command to clear the console screen as it belongs to the shell. I found a workaround though. You can press the 'F2' menu button. Once the menu is show, you can press the "Enter" key to dismiss it. The screen will be cleared as a side effect. I don't know this is per design or not. But this is so far the easiest way that I found to clear screen.

I don't think shell command on Windows works at all.

**Comment by jebr** [comment]
> I think you have to run the shell command to clear the console screen as it belongs to the shell. I found a workaround though. You can press the 'F2' menu button. Once the menu is show, you can press the "Enter" key to dismiss it. The screen will be cleared as a side effect. I don't know this is per design or not. But this is so far the easiest way that I found to clear screen.
> 
> I don't think shell command on Windows works at all.

Thanks for your reply. Your solution doesn't do the trick for me on Windows. Found something on the internet. `CTRL + L` will clear the screen. 

https://www.geeksforgeeks.org/clear-screen-python/
