### ISSUE TITLE
Extending embedded ptpython

### ISSUE THREAD

**Issue by 0xcrypto** [prompt-toolkit/ptpython#377]
In my project https://github.com/hackberry-xyz/reconframe, I am shipping ptpython as the default interpreter. We have a specific requirement of having some custom menus, dialog boxes and stuff. For now, I am using ```embed()``` but it seems pretty much locked away from the script that invoked it. Can you guys help me out a little in this. Thank you :relaxed:

**Comment by sparvanders** [comment]
You can pass globals and locals to embed(), does that not solve the problem?
Example:
(https://github.com/prompt-toolkit/ptpython/blob/master/examples/python-embed.py)

**Comment by 0xcrypto** [comment]
Yeah I was able to use that but I was thinking of modifying the interface as well

**Comment by sparvanders** [comment]
You need to build your interface using the parent project prompt-toolkit https://github.com/prompt-toolkit/python-prompt-toolkit
I don't have any experience of this myself -- not a developer in this project.

**Comment by 0xcrypto** [comment]
aah cool. Thank you.

**Comment by 0xcrypto** [comment]
Closing this as I found a solution. It is possible to configure ptpython by providing a [callback function](https://github.com/prompt-toolkit/ptpython/blob/master/examples/ptpython_config/config.py):

```python
from config import configure

embed(configure=configure)
```
