### ISSUE TITLE
Remove black from install_requires

### ISSUE THREAD

**Issue by ObserverOfTime** [prompt-toolkit/ptpython#413]
`black` is not needed for the program to function and should be in `extras_require` instead.

**Comment by jonathanslenders** [comment]
It is required for ptpython however, because it's used for output formatting on the REPL.

**Comment by cblegare** [comment]
hello there, sorry for reviving this closed issue.

It is good to know that black depends on `typed-ast`, which is incompatible with most non CPython compilers (like pypy).  Having a way to not necessarily rely on black could be interesting

**Comment by jonathanslenders** [comment]
Ok, I didn't know that. Feel free to create a PR to make black optional.
