### ISSUE TITLE
KeyError: '__pt_repr__'

### ISSUE THREAD

**Issue by horseinthesky** [prompt-toolkit/ptpython#417]
Hello.
Just started using `ptpython` instead of `ipython`. Like it a lot.

One thing that bothers me at the moment is: I have custom class that has a `__repr__`; however when I try to repr it:
```
In [4]: print(d)
{'start': {'time': '10:00'}, 'end': {'time': '08:00'}}

In [5]: type(d)
Out[5]: <class 'ej2.JSONObject'>

In [6]: d
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ptpython/repl.py", line 129, in _process_text
    await self._execute(line)
  File "/usr/lib/python3.9/site-packages/ptpython/repl.py", line 182, in _execute
    await self.show_result(result)
  File "/usr/lib/python3.9/site-packages/ptpython/repl.py", line 214, in show_result
    if hasattr(result, "__pt_repr__"):
  File "/home/horseinthesky/ej2.py", line 33, in __getattr__
    return self[name]
  File "/home/horseinthesky/ej2.py", line 46, in __getitem__
    return self._data[key]
KeyError: '__pt_repr__'

'__pt_repr__'
```
I get `KeyError`.

If I understood [this](https://github.com/prompt-toolkit/ptpython/blob/master/README.rst#__pt_repr__-a-nicer-repr-with-colors) correctly `ptpython` should call `__pt_repr__` only if it is implemented?!

How can I fix it? Thank you.

**Comment by jonathanslenders** [comment]
I think the problem is that ``__getattr__`` is supposed to raise an ``AttributeError`` if the attribute is not there. Not a ``KeyError``

We could (and probably should) handle this in ptpython, but I think your ``__getattr__`` implementation should turn the ``KeyError`` back into an ``AttributeError``.

**Comment by horseinthesky** [comment]
Yes, you are right. Raising `AttributeError` in `__getattr__` fixes the issue.

```
We could (and probably should) handle this in ptpython, but I think your __getattr__ implementation should turn the KeyError back into an AttributeError.
```
Should I leave the issue open until you fix it? Thank you.

**Comment by jonathanslenders** [comment]
Fix: https://github.com/prompt-toolkit/ptpython/pull/422

**Comment by jonathanslenders** [comment]
It was fixed. Thanks again for reporting the issue!
