### ISSUE TITLE
Creating a ptpython pane inside another prompt_toolkit UI

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [prompt-toolkit/ptpython#450]
Hi @jonathanslenders I'm hoping you can give me some advice here. We are trying to build a prompt_toolkit app for interacting with devices over [pyserial](https://github.com/pyserial/pyserial). We'd like it to be a full screen app and have at least two panes: one for displaying log messages from pyserial connected devices and one for an interactive python repl.

![Screenshot_2021-04-06_11-26-02](https://user-images.githubusercontent.com/37681/113760767-7cb9a200-96cb-11eb-9f3b-aca6aeac124b.png)
Here's the layout:
```python
self.python_pane = PythonPane()
self.root_container = FloatContainer(
    content=HSplit(
        [
            self.top_toolbar,
            self.log_pane,
            self.split_window,
            self.python_pane.window,
            self.bottom_toolbar,
        ],
    ),
    floats=[
        # Message Echo Area
        Float(bottom=1, left=0, right=0, height=1,
                content=MessageToolbarBar(self)),
        # Floating Help Window
        Float(
            content=HelpWindow(self),
            right=2, top=2,
        ),
    ],
)
```

To kick off the pt app I have:
```python
async def run(self):
    """Start the prompt_toolkit UI."""
    background_log_task = asyncio.create_task(self.log_forever())
    try:
        unused_result = await self.application.run_async(
            set_exception_handler=True)
    finally:
        background_log_task.cancel()
    print("Quitting event loop. Bye.")
```

The `PythonPane()` class is a bunch of stuff copy pasted (for experimentation) from [ptpython/repl.py](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/repl.py) and [ptpython/python_input.py](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/python_input.py) but without the bits to create a new a new `prompt_toolkit` application (from [here](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/python_input.py#L382)). I also moved a bunch of logic from `run()` and `eval()` [here in repl.py](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/repl.py#L93) and moved it into the `_accept_handler` [here](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/python_input.py#L387)

The goal being to allow embeding into an existing app. Some questions:

1. Is this a good way to do this? If yes would you accept a pull request to support this use case? I think it would have to refactor the parts that create a new app and layout outside of the `PythonInput` class and provide an example of how to override the `accept_handler`.
2. Am I better off writing my own repl like https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/full-screen/calculator.py
3. Can ipython support rendering other `prompt_toolkit` containers in it's UI that are updated asynchronously?

Thanks for any feedback you can provide!

**Comment by AnthonyDiGirolamo** [comment]
Ok so I have this somewhat working with this change:
https://github.com/AnthonyDiGirolamo/ptpython/commit/1e9508655cad46595d66245afd842bf46d306a2d

It allows to us to create our own `PwPtPythonRepl(repl.PythonRepl)` class. Like this: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/41580/9/pw_console/py/pw_console/pw_ptpython_repl.py Which can be part of our prompt_toolkit app. 

Currently it just logs the results instead of printing them. I still need to figure out how to make [this bit](https://github.com/AnthonyDiGirolamo/ptpython/blob/ptpython-library/ptpython/repl.py#L524) not print to stdout and just return the formatted text instead.

**Comment by lfvjimisola** [comment]
Is there any documentation on how to use this functionality?
