### ISSUE TITLE
Environment Python not respected

### ISSUE THREAD

**Issue by phipsgabler** [prompt-toolkit/ptpython#464]
From [here](https://github.com/prompt-toolkit/ptpython/issues/58#issuecomment-125174144): 
> ptpython starts with the Python version defined by the python executable. Basically whatever /usr/bin/env python returns.

Well... with ptpython installed globally with pip,

```
> conda create -n test python=2.7
> conda activate test
> which python
/home/pgabler/miniconda3/envs/test/bin/python
> python --version
Python 2.7.18 :: Anaconda, Inc.
> /usr/bin/env python --version
Python 2.7.18 :: Anaconda, Inc.
> ptpython
>>>

 
[F4] Emacs  7/7 [F3] History [F6] Paste mode ... [F2] Menu - CPython 3.8.5 
```

Appearently it doesn't use "whatever `/usr/bin/env python` returns (and also doesn't find packages within some environment). So how to I get to use it the environment Python instead of the system one? This is on Ubuntu 20.04, with ptpython 3.0.18.

I would like to avoid installing ptpython in each environment separately.

**Comment by jonathanslenders** [comment]
This is the only way. ptpython has to be installed in each environment.
I'm pretty sure the same is true for IPython/bpython/...

**Comment by phipsgabler** [comment]
Hm, ok.  You're right, that's a behaviour I hate about IPython, and the reason I considered switching to ptpython.  How unfortunate.

Unless you consider this a docs issue, feel free to close.
