### ISSUE TITLE
Can't exit from ptpython 3.0.18

### ISSUE THREAD

**Issue by yatmanov** [prompt-toolkit/ptpython#465]
@jonathanslenders, thank you for the great tool!

Few days ago after I upgrade to ptpython version 3.0.18 I found out I can no longer exit from repl using either `exit()` or `raise SystemExit`.
I think the changes caused the issue is in commit 321d9e177d42de782790740927a4e7a45c3cb7b3. There on line 101 should be `raise` instead on `return`. Changing this line to `raise` fixes #463 too.
I can try to work on the fix if you don't mind.

**Comment by jonathanslenders** [comment]
Possible fix: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1457
Would be great if you could try it out, if you have some time.

**Comment by jonathanslenders** [comment]
Good point, it's indeed line 101! I'll fix it here in ptpython. But the "fix" in prompt_toolkit probably doesn't hurt either.

**Comment by yatmanov** [comment]
@jonathanslenders, 3.0.19 works well now. I'll close this issue. Thank you! 

I'm not sure, but I think we should change `return` to `raise` in the `run_and_show_expression_async` function too.
