### ISSUE TITLE
Getting "Cannot create a file when that file already exists" for custom config file

### ISSUE THREAD

**Issue by wasi-master** [prompt-toolkit/ptpython#495]
The traceback
```python
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wasi Master\AppData\Roaming\Python\Python39\Scripts\ptpython.exe\__main__.py", line 7, in <module>
  File "C:\Users\Wasi Master\AppData\Roaming\Python\Python39\site-packages\ptpython\entry_points\run_ptpython.py", line 159, in run
    config_file, history_file = get_config_and_history_file(a)
  File "C:\Users\Wasi Master\AppData\Roaming\Python\Python39\site-packages\ptpython\entry_points\run_ptpython.py", line 106, in get_config_and_history_file
    pathlib.Path(d).mkdir(parents=True, exist_ok=True)
  File "C:\Program Files\Python39\lib\pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Wasi Master\\AppData\\Local\\prompt_toolkit\\ptpython\\config.py'
```

Looking at the Path.mkdir documentation

> If *exist_ok* is true, [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) exceptions will be ignored (same behavior as the POSIX mkdir -p command), but only if the last path component is not an existing non-directory file.

But the clause "but only if the last path component is not an existing non-directory file." is a bit confusing for me since I'm not a native English speaker. Am I doing something wrong? Thanks in advance :)

**Comment by cibinmathew** [comment]
@wasi-master 
1. Can you provide the steps to reproduce
2. How did you start the prompt. 
3. Did you use any config

**Comment by wasi-master** [comment]
@cibinmathew Thank you very much for responding. But alas, I cannot reproduce this issue anymore, it got fixed on its own somehow. Sorry for the inconvenience

**Comment by wasi-master** [comment]
I just realized my config had a SyntaxError in it and it wasn't getting used by ptpython for some reason. Shouldn't it show some error message saying that my config is invalid? Anyways, upon fixing that SyntaxError, this started happening again, so I'm reopening the issue.

I'm running Windows 11, trying on WSL with windows, the config works perfectly, so there shouldn't be a problem with that, even with the default config file demo shown in this repo. I've tried with and without the `PTPYTHON_CONFIG_HOME` environment variable and both show the same error. I started the prompt with the usual `ptpython` command and also tried `python -m ptpython`. One thing to be noted is that I have multiple python versions installed on my system and all of them have ptpython, but that shouldn't matter since the config file isn't interpreter specific

I don't have multiple machines at the moment so I can't say the exact steps to reproduce, but here's an attempt
1. Use a windows machine, preferably windows 11
2. In the directory: `C:\Users\<your_name>\AppData\Local\prompt_toolkit\ptpython`, add a file called `config.py` with the contents same as [this file](https://github.com/prompt-toolkit/ptpython/blob/master/examples/ptpython_config/config.py)
3. Run ptpython

**Comment by cibinmathew** [comment]
will check if this can be reproduced in Ubuntu/Mac. Unfortunately no windows with me :-( 
@wasi-master in case if any stacktrace can be exported or any useful additional info, that can be helpful

**Comment by wasi-master** [comment]
Okay, I'll first do some debugging on my end and notify you :)

**Comment by wasi-master** [comment]
OH! this was just a mistake on my end. I accidentally ended up putting a file path instead of a folder path in my PTPYTHON_CONFIG_HOME environment variable. Sorry for wasting your time, I'm clumsy at times
