### ISSUE TITLE
[feature] Can it support ANSI escape code?

### ISSUE THREAD

**Issue by Freed-Wu** [prompt-toolkit/ptpython#505]
![Screenshot from 2022-08-22 19-00-08](https://user-images.githubusercontent.com/32936898/185905902-93f27740-2408-47d9-b6af-15d95a6d6878.png)

Thanks.

**Comment by Freed-Wu** [comment]
It looks like the problem that plotext uses ansi escape code.

This is `pydoc plotext.sin` in shell and `help(plotext.sin)` in python:

![screen-2023-01-13-19-49-54](https://user-images.githubusercontent.com/32936898/212313875-bc95d556-907c-49cd-86e6-6413ccf7d687.jpg)

python doesn't support ansi escape codes in docstring, even if pydoc and `help()`.

@piccolomo

**Comment by piccolomo** [comment]
Interesting, would you like me to work on docstrings free from ansi codes for next version?

**Comment by Freed-Wu** [comment]
>  docstrings free from ansi codes for next version

I think it is an easy solution to `help()` or `pydoc` correctly :smile:

**Comment by piccolomo** [comment]
Cool, I would work on it (may take some time till I get back coding). Feel free to open an issue about it to get updated. Otherwise hopefully I remember to write here and update.

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

Sorry for such long break. 

The new version (only on GitHub for now) has also docstrings free from ansi codes. 

The docstrings are explained [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#docstrings) and the installing instructions are [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#install).

All the best,
Savino
