### ISSUE TITLE
No option in config.py to set Reformat output or Enable pager

### ISSUE THREAD

**Issue by sockduct** [prompt-toolkit/ptpython#521]
In the example config.py file:
https://github.com/prompt-toolkit/ptpython/blob/master/examples/ptpython_config/config.py

I don't see options to set the following ptpython menu options:
1) Reformat output (black):  On/Off
2) Enable pager for output:  On/Off

**Comment by plutonium-239** [comment]
According to [repl.py](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/repl.py), these options should be:
`repl.enable_output_formatting` [L127](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/repl.py#L127)
`repl.enable_pager` [L129](https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/repl.py#L129)

This might also be of interest (looks like the definitions of the config variables): https://github.com/prompt-toolkit/ptpython/blob/master/ptpython/python_input.py#L309
