### ISSUE TITLE
Enable modal (vi) cursor in config.py

### ISSUE THREAD

**Issue by teroyks** [prompt-toolkit/ptpython#548]
How do you set the cursor shape to Modal in `config.py`?

**Comment by mohamed-180** [comment]
In your `config.py` you can add 

```  
  repl.cursor_shape_config = 'Blink under'
```
under the `def configure(repl):
` function .

**Comment by teroyks** [comment]
@mohamed-180 Thanks, that did the trick!

I added a PR to include this setting in the config example so that others can find it too.
