### ISSUE TITLE
support XDG spec

### ISSUE THREAD

**Issue by flying-sheep** [prompt-toolkit/ptpython#63]
please use [`appdirs`](https://pypi.python.org/pypi/appdirs/1.4.0) to not pollute my `$HOME` with a `.ptpython` directory.

with `dirs = AppDirs('ptpython', 'Jonathan Slenders')`, your stuff should go into `dirs.user_data_dir`, `dirs.user_config_dir`, and  `dirs.user_cache_dir`

**Comment by Carreau** [comment]
> please use appdirs

I think we might have duplicated part of this code in recent jupyter to have things in ~/Library on Mac OS
we should have a look at this lib.

**Comment by flying-sheep** [comment]
it’s really good in that it does exactly the right thing for every platform.

nice abstraction of all the concepts (local/remote appdata on windows, multiple dirs on linux, …)

**Comment by jonathanslenders** [comment]
Ok, probably I'll use appdirs.

First, I was hesitating, because I really don't like to add another dependency, especially for something simple like this. (Actually, I think this should become part of Python itself, as in ``os.path`` somewhere.)

**Comment by flying-sheep** [comment]
yeah, that’s really something stdlib-worthy.

about dependencies: i feel the same sentiment when adding dependencies to my stuff, but when really thinking about it, there’s no reason: why not add another tiny lib as dependency? it really should be preferable to have that stuff in `site-packages/appdirs.py` instead of an inferior impromptu hacked clone in `site-packages/<yourmodule>/utils/dirs.py`.

the rust community has no qualms about that: the cargo ecosystem has thousands of really tiny modules and many things have dozens of dependencies.

**Comment by Carreau** [comment]
+1 to your mail to Python ideas. :-)

**Comment by flying-sheep** [comment]
:blush:

**Comment by ryneeverett** [comment]
> about dependencies: i feel the same sentiment when adding dependencies to my stuff, but when really thinking about it, there’s no reason: why not add another tiny lib as dependency? it really should be preferable to have that stuff in site-packages/appdirs.py instead of an inferior impromptu hacked clone in site-packages/<yourmodule>/utils/dirs.py.

Hoping for a response to this because I'd like to learn the reasoning behind the anti-dependency philosophy.

**Comment by jonathanslenders** [comment]
There are several reasons. Maybe we don't know the authors of the other libraries. (How are they going to respond to bugs or feature requests?) Maybe it's even not anymore or badly maintained, or not stable. Maybe they have a very different way of coding. And what if it's removed from Pypi? Typically, less dependencies is less chance for failure.

But of course, code duplication is definitely not an alternative to dependencies, and many times it's okay to add a dependency.

@flying-sheep: thanks for your mail to python-ideas!

**Comment by Carreau** [comment]
> Hoping for a response to this because I'd like to learn the reasoning behind the anti-dependency philosophy.

There is also (IMHO) generally a strong historical background that in Python dependencies where really hard to deal with. Less nowadays that pip works, but still not perfect. Libraries authors that remember the bad time of pip tend to be reluctant to dependencies, and communicate that to new ones.

**Comment by flying-sheep** [comment]
well, there should be no issue in adding a dependency and later, if something happens that necessitates this, just vendor it. (put it into your own repo)

**Comment by carlwgeorge** [comment]
:+1: I would love for ptpython to respect my `XDG_CONFIG_HOME` variable.
