### ISSUE TITLE
Using pt(i)python while in a virtualenv uses the system install instead of local install

### ISSUE THREAD

**Issue by lynncyrin** [prompt-toolkit/ptpython#77]
tell me if I need to explain the issue in more detail?

(it should be noted that I really didn't need a system install of ptpython, and uninstalling it fixed the issue)

**Comment by pombredanne** [comment]
@LynnCo Are you sure: I cannot reproduce this:
Here I am in an activated virtual env: /home/pombreda/tmp/ptpy:
```
$ pip install ptpython
$ ptpython 
>>> import sys
>>> sys.executable
'/home/pombreda/tmp/ptpy/tmp/bin/python2'
```
The exe is the venv exe, not the system exe
If I invoke ptpython in a non activated venv, there again, the venv python is used alright too.

**Comment by pombredanne** [comment]
FWIW, there would no way for ptpython to escape the virtualenv... that would be rather tricky... because this is processed at install time where eventually ptpython cannot do anything.

My hunch: you have a system-wide install of ptpython that is in your path and that might take over the venv, but there again that would be a rather suspect behaviour

**Comment by pombredanne** [comment]
Actually just to be accurate, unless your venv is activated and if you have both a library (any python library) installed both system-wide and locally in your venv, you will by default get whatever is in your path, as it should. This is normal. 

Here the venv is not activated. ptpython is installed both locally and globally.
The default ptpython is the system one:
```
$ which ptpython
/usr/local/bin/ptpython
```

Now I activate the venv and the ptpython used is the local one:
```
$ source tmp/bin/activate
(tmp)$ which ptpython
/home/pombreda/tmp/ptpy/tmp/bin/ptpython
```

Alternatively, you can invoke the local  ptpython `/home/pombreda/tmp/ptpy/tmp/bin/ptpython` by pointing to the bin/ptpython in your venv even if not activated.

Note that there are numerous wrapper scripts for virtualenv to automatically `activate` when you navigate to a dir that contains a virtualenv.

**Comment by kernc** [comment]
I run ptipython with activated virtualenv. I get `np` if I type:
```py
import numpy as np
```
I don't get `np`, however, if I run the same ptipython in the same virtualenv with:
```bash
$ alias ipy='ptipython --interactive ~/.ptipython/autoload.py'  # autoload.py containing said import
$ ipy
```
The numpy import fails.

Is this related?

**Comment by kernc** [comment]
Never mind. The import statement was inside a try-except block. Without it, it works.
But _that_ is an oddity of its own. :smile:

**Comment by CookiesBestDinner** [comment]
Bash caches locations of executables
So after changing things up in the search-path, one might need to clear that cache to get a consistent result (if adding something earlier in the search-path than something that was previously executed and therefore cached).

`hash -r` or re-activate the venv which likely clears it for you

(nothing to do with ptpython)

**Comment by lynncyrin** [comment]
♻️ closing some of my older github issues ♻️
